### ISSUE TITLE
Looks pretty similar to the extension I created a few months ago spa5k/uids-postgres

### ISSUE THREAD

**Issue by spa5k** [t3hmrman/pg_idkit#3]
No hard feeling or something, it just feels great that someone also thought of doing same as mine and saw potential in pgx. Well done and thanks for all these exotics ids, i never knew they existed. 

haha time for me to add them too and see what can we done here. 🚀👌

**Comment by spa5k** [comment]
Also if you need help for the docker image, I do have a template ready in my repo https://github.com/spa5k/uids-postgres , so it can help you i guess

**Comment by t3hmrman** [comment]
Yeah, there's a bunch of prior art for implementing these ID generation mechanisms -- `pgx` is an awesome toolkit, I can't wait to see what other people build with the ability to access the rust ecosystem.

This issue doesn't really have any actionable stuff for me so I'm going to go ahead and close it -- thanks for checking out the repo!

**Comment by t3hmrman** [comment]
@spa5k Hey I added a prior art section in the README -- I noted it in the Supabase post but it hit me that it's obvious to include in this repo as well so people can find *both* projects!

If you know any more feel free to add em or open up a PR/etc!

**Comment by spa5k** [comment]
Hey thanks for it! 🎉

**Comment by spa5k** [comment]
Lol one thing, it's spa5k, not spa25k, there's spelling mistake in readme

**Comment by t3hmrman** [comment]
Oh sorry that's a typo -- I got the link right but somehow not the spelling :facepalm:
